MISC ARRAY FUNCTIONS

>>>>>,[>,] TAKE INPUT TO ARRAY
?
<[<]> MOVE TO FIRST ELEMENT OF ARRAY FROM RIGHT "WALL" OF ARRAY
<<<<<<< MOVE AWAY AN ARBITRARY AMOUNT
?
+[->+] MOVE BACK TO FIRST ELEMENT OF ARRAY GIVEN AT A BUNCH OF ZEROES
?